logging:
  file:
    path: /data/logs/file-server
file-server:
  workspace: /data/file-server
  host: http://localhost:8080
server:
  servlet:
    context-path: /file-server
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      file-size-threshold: 2MB
  application:
    name: file-server
  http:
    encoding:
      force: true
